export const userActions = {
  MENU_USER: 'MENU_USER',
  MENU_ROLE: 'MENU_ROLE',
  MENU_FRIDGE: 'MENU_FRIDGE',
  USER_CREATE: 'USER_CREATE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  FRIDGE_CREATE: 'FRIDGE_CREATE',
  FRIDGE_UPDATE: 'FRIDGE_UPDATE',
  FRIDGE_DELETE: 'FRIDGE_DELETE',
};
